In [2]:
%matplotlib inline
from keras.utils.vis_utils import plot_model
from keras.models import Model,Sequential
from tensorflow.keras.utils import to_categorical
from keras.layers import Input, Dense, Dropout
from tensorflow.keras.optimizers import SGD
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt  

In [7]:
data = pd.read_csv("dataset.csv")
data.head()

battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [8]:
print(data.shape)
train=[]
for i in range(data.shape[0]):
  train.append(list(data.iloc[i]))

(2000, 21)


In [9]:
x=[]
y=[]
for i in train:
  y.append(i[-1])
  x.append(i[:20])
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=29)


In [10]:
x_train = np.array(x_train)
y_train = np.array(y_train)
x_test = np.array(x_test)
y_test = np.array(y_test)
print(x_train)
print(y_train)

[[1.412e+03 1.000e+00 2.400e+00 ... 0.000e+00 0.000e+00 1.000e+00]
 [8.080e+02 1.000e+00 5.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.619e+03 1.000e+00 9.000e-01 ... 1.000e+00 0.000e+00 1.000e+00]
 ...
 [1.872e+03 1.000e+00 2.300e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.133e+03 0.000e+00 1.400e+00 ... 1.000e+00 0.000e+00 1.000e+00]
 [1.242e+03 1.000e+00 2.400e+00 ... 1.000e+00 0.000e+00 0.000e+00]]
[1. 0. 0. ... 2. 1. 0.]


In [11]:
y_train = to_categorical(y_train, 4)
y_test = to_categorical(y_test, 4)
print(y_test)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [12]:
model = Sequential()
model.add(Dense(32, input_dim=x_train.shape[1], activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(4, activation='softmax'))
### YOU HAVE TO MAKE YOUR CHANGES HERE !!!

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

history = model.fit(x_train, y_train,
                    epochs=300,
                    batch_size=32,
                    verbose=1,
                    validation_data=(x_test,y_test))

Epoch 1/300
50/50 [==============================] - 3s 8ms/step - loss: 79.6224 - accuracy: 0.3450 - val_loss: 12.0815 - val_accuracy: 0.4975
Epoch 2/300
50/50 [==============================] - 0s 4ms/step - loss: 23.3445 - accuracy: 0.4269 - val_loss: 5.1346 - val_accuracy: 0.4625
Epoch 3/300
50/50 [==============================] - 0s 4ms/step - loss: 10.8586 - accuracy: 0.4300 - val_loss: 1.2549 - val_accuracy: 0.4775
Epoch 4/300
50/50 [==============================] - 0s 4ms/step - loss: 5.3071 - accuracy: 0.3550 - val_loss: 1.1542 - val_accuracy: 0.4375
Epoch 5/300
50/50 [==============================] - 0s 4ms/step - loss: 2.2570 - accuracy: 0.3706 - val_loss: 1.1595 - val_accuracy: 0.4675
Epoch 6/300
50/50 [==============================] - 0s 4ms/step - loss: 1.8359 - accuracy: 0.3669 - val_loss: 1.1302 - val_accuracy: 0.4850
Epoch 7/300
50/50 [==============================] - 0s 4ms/step - loss: 1.4442 - accuracy: 0.3787 - val_loss: 1.1194 - val_accuracy: 0.4750
Epoch 8/3